version: '3.8'

services:
  veaero-optimizer:
    build: .
    container_name: veaero-optimizer
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    volumes:
      - ./settings.json:/app/settings.json:ro
      - ./transactions.json:/app/transactions.json:ro
      - ./epochs.json:/app/epochs.json:ro
      - ./screenshots:/app/screenshots
    restart: always
